const BEEHIIV_SIGNUP = '/opportunity-list'

export interface District {
  id: string
  slug: string
  name: string
  tagline: string
  emoji: string
  color: string
  colorDim: string
  icon: string
  description: string
  longDescription: string
  features: string[]
  cta: string
  href: string
  externalHref?: string
  mapX: number
  mapY: number
  size: 'xl' | 'lg' | 'md' | 'sm'
  terrain: 'island' | 'marina' | 'harbor' | 'bay' | 'pier' | 'district' | 'point' | 'vault'
  tag: string
  passportStamp: string
}

export const districts: District[] = [
  {
    id: 'founder-island',
    slug: 'founder-island',
    name: 'Founder Island',
    tagline: 'The Origin. The Mission. The Man.',
    emoji: '🏝️',
    color: '#c9a84c',
    colorDim: '#7a6230',
    icon: '⚜️',
    description: 'The central hub of the MysterMyself universe. Where Maurice Scott built the blueprint and the brand mission lives.',
    longDescription: 'Founder Island is ground zero for everything in the Scott-King Coast universe. This is where Maurice Scott\'s origin story, personal brand, and the entire ecosystem mission are documented and explored. The story behind the system.',
    features: ['The Origin Story', 'Ecosystem Blueprint', 'Brand DNA', 'Mission & Vision', 'Community Access'],
    cta: 'Explore the Origin',
    href: '/map/founder-island',
    externalHref: '/about',
    mapX: 50,
    mapY: 45,
    size: 'xl',
    terrain: 'island',
    tag: 'HQ',
    passportStamp: 'ORIGIN',
  },
  {
    id: 'market-marina',
    slug: 'market-marina',
    name: 'Market Marina',
    tagline: 'Where Gold Flows and Liquidity Docks.',
    emoji: '⚓',
    color: '#c9a84c',
    colorDim: '#7a6230',
    icon: '📊',
    description: 'The financial core — XAUUSD trading, market structure, liquidity sweeps, and the Trading Chef methodology.',
    longDescription: 'Market Marina is the trading hub of Scott-King Coast. Every ship that docks here carries market intelligence — liquidity sweeps, fair value gaps, institutional concepts, and the XAUUSD setups that power the Trading Chef brand. Where money is made on the charts.',
    features: ['XAUUSD Analysis', 'Market Structure', 'Liquidity Sweeps', 'Fair Value Gaps', 'Session Playbooks', 'Chart Reviews'],
    cta: 'Enter the Marina',
    href: '/map/market-marina',
    externalHref: '/trading-chef',
    mapX: 72,
    mapY: 30,
    size: 'lg',
    terrain: 'marina',
    tag: 'Trading',
    passportStamp: 'GOLD',
  },
  {
    id: 'route-harbor',
    slug: 'route-harbor',
    name: 'Route Harbor',
    tagline: 'Every Route is a Revenue Stream.',
    emoji: '🚢',
    color: '#0EA5E9',
    colorDim: '#0369A1',
    icon: '🚚',
    description: 'The logistics and courier income operations center. Medical Courier Insider Edge, contract delivery, and road-based income systems.',
    longDescription: 'Route Harbor is where the road warriors dock. The Medical Courier Insider Edge program lives here — helping you find pharmacy, lab, and medical courier opportunities without depending only on job boards or delivery apps. Courier Income Lab is the research engine inside Route Harbor.',
    features: ['Medical Courier Insider Edge — $37', 'Pharmacy & Lab Route Research', 'Contract Delivery Systems', 'Route Acquisition Math', 'Vehicle Strategy', 'Courier Income Lab (Inside Route Harbor)'],
    cta: 'Get the Free Courier Chapter',
    href: '/map/route-harbor',
    externalHref: BEEHIIV_SIGNUP,
    mapX: 22,
    mapY: 35,
    size: 'lg',
    terrain: 'harbor',
    tag: 'Logistics',
    passportStamp: 'ROUTE',
  },
  {
    id: 'blueprint-bay',
    slug: 'blueprint-bay',
    name: 'Blueprint Bay',
    tagline: 'Reserved. Systems Loading.',
    emoji: '📐',
    color: '#22C55E',
    colorDim: '#15803D',
    icon: '📚',
    description: 'Reserved for AI automation, agents, workflows, dashboards, and operating systems.',
    longDescription: 'Reserved for AI automation, agents, workflows, dashboards, and operating systems. Blueprint Bay is under construction — this district will house the complete AI-powered business OS for the MysterMyself ecosystem when it opens.',
    features: ['AI Automation Systems', 'Agent Workflows', 'Custom Dashboards', 'Operating Systems', 'Business OS Templates', 'Coming Soon'],
    cta: 'Join the List',
    href: '/map/blueprint-bay',
    mapX: 35,
    mapY: 65,
    size: 'md',
    terrain: 'bay',
    tag: 'Playbooks',
    passportStamp: 'BLUEPRINT',
  },
  {
    id: 'creator-pier',
    slug: 'creator-pier',
    name: 'Creator Pier',
    tagline: 'Content. AI. Automation. Revenue.',
    emoji: '🎬',
    color: '#A855F7',
    colorDim: '#7C3AED',
    icon: '🤖',
    description: 'Where content meets automation. AI workflows, creator systems, and the digital infrastructure behind the ecosystem.',
    longDescription: 'Creator Pier is the content and automation engine of Scott-King Coast. AI-powered workflows, Claude and ChatGPT prompt libraries, content systems, and the digital business operating system that runs behind the scenes of every MysterMyself brand.',
    features: ['AI Business OS', 'Claude Workflows', 'Content Systems', 'Prompt Libraries', 'Automation Playbooks', 'Creator Economy Tools'],
    cta: 'Build on the Pier',
    href: '/map/creator-pier',
    externalHref: '/about',
    mapX: 75,
    mapY: 62,
    size: 'md',
    terrain: 'pier',
    tag: 'AI Creator',
    passportStamp: 'CREATOR',
  },
  {
    id: 'flavor-district',
    slug: 'flavor-district',
    name: 'Flavor District',
    tagline: 'Recipes Into Revenue. Wings Into Wealth.',
    emoji: '🍗',
    color: '#c0392b',
    colorDim: '#7f1d1d',
    icon: '🔥',
    description: 'The food business and culinary brand district. Breaded Or Not?! catering systems, pop-up playbooks, and food entrepreneurship.',
    longDescription: 'Flavor District is where hustle meets hunger. The Breaded Or Not?! brand lives here — pop-up operation systems, catering business frameworks, menu development, brand building, and the complete food entrepreneur playbook. Turn your recipe into real revenue.',
    features: ['Breaded Or Not?!', 'Pop-Up Systems', 'Catering Framework', 'Menu Development', 'Food Brand Playbook', 'Revenue Operations'],
    cta: 'Enter the District',
    href: '/map/flavor-district',
    externalHref: '/breaded',
    mapX: 18,
    mapY: 60,
    size: 'md',
    terrain: 'district',
    tag: 'Food Biz',
    passportStamp: 'FLAVOR',
  },
  {
    id: 'legacy-point',
    slug: 'legacy-point',
    name: 'Legacy Point',
    tagline: 'The Academy. The Curriculum. The Transformation.',
    emoji: '🎓',
    color: '#c9a84c',
    colorDim: '#7a6230',
    icon: '🏛️',
    description: 'Trading Chef University — the premium 6-module gold trading curriculum for complete mastery of XAUUSD.',
    longDescription: 'Legacy Point is the educational pinnacle of Scott-King Coast. Trading Chef University\'s full curriculum lives here — 6 modules covering market structure foundations through psychology and live execution. This is where legacy traders are built, not born.',
    features: ['6-Module Curriculum', 'Market Structure Mastery', 'Liquidity Theory', 'Psychology & Mindset', 'Live Execution', 'Community & Mentorship'],
    cta: 'Claim Your Legacy',
    href: '/map/legacy-point',
    externalHref: '/trading-chef-university',
    mapX: 60,
    mapY: 20,
    size: 'lg',
    terrain: 'point',
    tag: 'Academy',
    passportStamp: 'LEGACY',
  },
  {
    id: 'fantasy-island',
    slug: 'fantasy-island',
    name: 'Fantasy Island',
    tagline: 'Draft Smart. Automate the Board. Stack the Edge.',
    emoji: '🏈',
    color: '#22C55E',
    colorDim: '#15803D',
    icon: '🏆',
    description: 'Game destination and live-update automation district for fantasy football. Draft Bible, rankings, injury alerts, subscriber drops, XP, rewards, and the TCU/trading simulation bridge.',
    longDescription: 'Fantasy Island is a game destination and live-update automation district for fantasy football. The Draft Bible, rankings, injury and news alerts, subscriber segments, Beehiiv drops, XP rewards, unlocks, and the TCU/trading simulation bridge all live here. Where competitive play meets automated income infrastructure.',
    features: ['Fantasy Draft Bible', 'Live Injury & News Alerts', 'Automated Rankings Updates', 'Subscriber Segments & Beehiiv Drops', 'XP Rewards & Unlocks', 'TCU / Trading Simulation Bridge'],
    cta: 'Get Fantasy Island Live Drops',
    href: '/map/fantasy-island',
    externalHref: BEEHIIV_SIGNUP,
    mapX: 82,
    mapY: 78,
    size: 'md',
    terrain: 'island',
    tag: 'Fantasy',
    passportStamp: 'FANTASY',
  },
  {
    id: 'library-vault',
    slug: 'library-vault',
    name: 'Library Vault',
    tagline: 'Free Knowledge. Unrestricted Access.',
    emoji: '📖',
    color: '#94A3B8',
    colorDim: '#475569',
    icon: '🗄️',
    description: 'The free resource library. Guides, frameworks, and starter content for every income lane — no purchase required.',
    longDescription: 'Library Vault is where generosity lives. Free guides, starter frameworks, intro content, and educational resources across every income lane in the ecosystem. The knowledge is here — the only cost is showing up. Start here, build everywhere.',
    features: ['Free Guides', 'Starter Frameworks', 'Educational Content', 'Resource Library', 'Community Drops', 'Intro Playbooks'],
    cta: 'Open the Vault',
    href: '/map/library-vault',
    externalHref: '/free-content',
    mapX: 42,
    mapY: 80,
    size: 'sm',
    terrain: 'vault',
    tag: 'Free',
    passportStamp: 'VAULT',
  },
]

export function getDistrict(slug: string): District | undefined {
  return districts.find((d) => d.slug === slug)
}
